### ISSUE TITLE
Include command with dependecy spec in the README

### ISSUE THREAD

**Issue by hsolg** [lambdaisland/nrepl-proxy#2]
This was a very useful tool! For beginners like me, it would be great to have the full command needed to run it from anywhere in the README. Something like this:

```
clj -Sdeps '{:deps {com.lambdaisland/nrepl-proxy {:mvn/version "0.2.8-alpha"}}}' -X lambdaisland.nrepl-proxy/start :port 1234 :attach 5678
```

**Comment by plexus** [comment]
That's a great idea! A PR to add that would be appreciated
